Acies/PresentationLayer/Controllers/PalletController.cs
using DataLayer.Pallets;
using LogicLayer.pallet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models.Entities;
using PresentationLayer.Models.PalletController;

namespace PresentationLayer.Controllers;
[Authorize]
public class PalletController : Controller
{
    private readonly IPalletService _palletService;
    public PalletController(IPalletService palletService)
    {
        _palletService = palletService;
    }
    public ViewResult Create()
    {
        ViewModelPallet pallet = new ViewModelPallet();
        return View(pallet);
    }

    public ViewResult Pallets()
    {
        IEnumerable<ViewModelPallet> pallets = _palletService.GetPallets().Select(pallet => new ViewModelPallet(pallet));
        ListPallets palletsList = new ListPallets { Pallets = pallets };
        return View("Pallets", palletsList);
    }
    [HttpPost]
    public IActionResult Create(ViewModelPallet pallet)
    {
        if (!ModelState.IsValid)
            return View("Create", pallet);
        bool success = _palletService.AddPallet(pallet);
        if (!success)
        {
            //maybe add validation on model properties
            ModelState.AddModelError(string.Empty, "Unable to save the pallet. Please try again.");
            return View("Create", pallet);
        }
        return Pallets();
    }


    public IActionResult Edit(Guid id)
    {
        Pallet? pallet = _palletService.GetPallet(id);
        if (pallet == null)
            return Pallets();
        return View(pallet);
    }
    [HttpPost]

    public IActionResult Edit(ViewModelPallet pallet)
    {
        if (!ModelState.IsValid)
        return View();
        bool update = _palletService.UpdatePallet(pallet);
       
        return Pallets();
    }

    public IActionResult Profile(Guid id)
    {
        Pallet? pallet = _palletService.GetPallet(id);
        if (pallet == null)
            return Pallets();
        return View(pallet);
    }


    public IActionResult Delete(Guid id)
    {
        
        bool delete = _palletService.DeletePallet(id);
        //maybe add success/failure
       
        return Pallets();
    }

}

Acies/PresentationLayer/Views/Pallet/Create.cshtml
@model Pallet

<h1>Create Pallet</h1>

<form asp-action="Create" method="post" class="m-2">
<div asp-validation-summary="All"></div>
<table>
    <tr>
        <td>
            <label asp-for="Id">ID</label>
            <input asp-for="Id" readonly/>
        </td>
        <td>
            <label asp-for="Description">Description</label>
            <input asp-for="Description" />
        </td>
        <td>
            <label asp-for="PalletMaterial">Material</label>
            <input asp-for="PalletMaterial" />
        </td>
    </tr>
    <tr>
        <td>
            <label asp-for="Dimensions.X">Width</label>
            <input asp-for="Dimensions.X" />
        </td>
        <td>
            <label asp-for="Dimensions.Y">Height</label>
            <input asp-for="Dimensions.Y" />
        </td>
        <td>
            <label asp-for="Dimensions.Z">Length</label>
            <input asp-for="Dimensions.Z" />
        </td>
    </tr>
    <tr>
        <td>
            <label asp-for="Weight">Weight</label>
            <input asp-for="Weight" />
        </td>
        <td>
            <label asp-for="MaxHeight">Max height</label>
            <input asp-for="MaxHeight" />
        </td>
        <td>
            <label asp-for="MaxWeight">Max weight</label>
            <input asp-for="MaxWeight" />
        </td>
    </tr>
    <tr>
        <td>
            <label asp-for="OverReach">OverReach</label>
            <input asp-for="OverReach" />
        </td>
        <td>
            <label asp-for="Spots">Spots</label>
            <input asp-for="Spots" />
        </td>
        <td>
            <label asp-for="SpecialCargo">SpecialCargo</label>
            <input asp-for="SpecialCargo" />
        </td>
    </tr>
    <tr>
        <td>
            <label asp-for="SpaceBetween">SpaceBetween</label>
            <input asp-for="SpaceBetween" />
        </td>
        <td>
            <label asp-for="PalletGroup">Pallegrouppe</label>
            <input asp-for="PalletGroup" />
        </td>
    </tr>
</table>



    <div class="d-flex gap-3">
        <button class="btn btn-success ms-auto" type="cancel" asp-action="Pallets">Cancel</button>
        <button class="btn btn-success" type="submit">Create</button>
    </div>
</form>

Acies/PresentationLayer/Views/Pallet/Edit.cshtml
@model Pallet

<h2>Edit Pallet</h2>

<form asp-action="Edit" method="post">

<table>
    <tr>
        <td>
            <label asp-for="Id">ID</label>
            <input asp-for="Id" readonly />
        </td>
        <td>
            <label asp-for="Description">Description</label>
            <input asp-for="Description" />
        </td>
        <td>
            <label asp-for="PalletMaterial">Material</label>
            <input asp-for="PalletMaterial" />
        </td>
    </tr>
    <tr>
        <td>
            <label asp-for="Dimensions.X">Width</label>
            <input asp-for="Dimensions.X" />
        </td>
        <td>
            <label asp-for="Dimensions.Y">Height</label>
            <input asp-for="Dimensions.Y" />
        </td>
        <td>
            <label asp-for="Dimensions.Z">Length</label>
            <input asp-for="Dimensions.Z" />
        </td>
    </tr>
    <tr>
        <td>
            <label asp-for="Weight">Weight</label>
            <input asp-for="Weight" />
        </td>
        <td>
            <label asp-for="MaxHeight">Max height</label>
            <input asp-for="MaxHeight" />
        </td>
        <td>
            <label asp-for="MaxWeight">Max weight</label>
            <input asp-for="MaxWeight" />
        </td>
    </tr>
    <tr>
        <td>
            <label asp-for="OverReach">OverReach</label>
            <input asp-for="OverReach" />
        </td>
        <td>
            <label asp-for="Spots">Spots</label>
            <input asp-for="Spots" />
        </td>
        <td>
            <label asp-for="SpecialCargo">SpecialCargo</label>
            <input asp-for="SpecialCargo" />
        </td>
    </tr>
    <tr>
        <td>
            <label asp-for="SpaceBetween">SpaceBetween</label>
            <input asp-for="SpaceBetween" />
        </td>
    </tr>
</table>


    <div class="d-flex gap-3">
        <button class="btn btn-success ms-auto" type="cancel" asp-action="Pallets">Cancel</button>
        <button class="btn btn-success" type="submit">Save Changes</button>
    </div>
</form>

Acies/PresentationLayer/Views/Pallet/Pallets.cshtml
@model ListPallets
    
<div>
    <h2>Paller</h2>
    <table class="table table-striped">
        <thead>
            <!--<th>
                ID
            </th>-->
            <th>
                Max højde
            </th>
            <th>
                Max vægt
            </th>
            <th>
                Materiale
            </th>
           
            <th></th><th></th>
            
            <th class="button">
                <!--
                <a asp-controller="Pallet" asp-action="Create">
                    <i class="bi bi-plus-square-fill"></i>
                </a>-->
            </th> 
        </thead>
        @foreach (Pallet p in Model?.Pallets!)
        {
        <tr>
            <!--<td>@p.Id</td>-->
            <td>@p.MaxHeight</td>
            <td>@p.MaxWeight</td>
            <td>@p.PalletMaterial</td>
            <td>
                    <a asp-controller="Pallet" asp-action="Profile" asp-route-Id="@p.Id" title="Se alle specifikationer">Detaljer</a>
            </td>
            <td class ="button">
                    <a asp-controller="Pallet" asp-action="Edit" asp-route-Id="@p.Id" title="Rediger palle">
                        <i class="bi bi-pencil-square"></i>
                </a>
            </td>
            <td class="button">
                <a asp-action="Delete" asp-route-Id="@p.Id" title="Slet palle" onclick="return confirm('Er du sikker på, at du vil slette denne palle?');">
                        <i class="bi bi-trash3-fill"></i>
                </a>
            </td>
        </tr>
        }
    </table>

    <div class="d-flex gap-3">
        <a class="btn btn-success ms-auto"  asp-controller="Pallet" asp-action="Create">Tilføj palle</a>
    </div>
</div>

Acies/PresentationLayer/Views/Pallet/Profile.cshtml
@model Pallet
@{
}
<div>
    <h2>Pallet Profile</h2>
    
    <table>
        <tr>
            <th>ID</th>
            <td>@Model.Id</td>
        </tr>
        <tr>
            <th>Beskrivelse</th>
            <td>@Model.Description</td>
        </tr>
        <tr>
            <th>Materiale</th>
            <td>@Model.PalletMaterial</td>
        </tr>
        <tr>
            <th>Bredde</th>
            <td>@Model.Dimensions.X mm</td>
        </tr>
        <tr>
            <th>Højde</th>
            <td>@Model.Dimensions.Y mm</td>
        </tr>
        <tr>
            <th>Længde</th>
            <td>@Model.Dimensions.Z mm</td>
        </tr>
        <tr>
            <th>Vægt</th>
            <td>@Model.Weight kg</td>
        </tr>
        <tr>
            <th>Max højde</th>
            <td>@Model.MaxHeight mm</td>
        </tr>
        <tr>
            <th>Max vægt </th>
            <td>@Model.MaxWeight kg</td>
        </tr>
        <tr>
            <th>OverReach</th>
            <td>@Model.OverReach</td>
        </tr>
        <tr>
            <th>Spots</th>
            <td>@Model.Spots</td>
        </tr>
        <tr>
            <th>SpecialCargo</th>
            <td>@Model.SpecialCargo</td>
        </tr>
        <tr>
            <th>SpaceBetween</th>
            <td>@Model.SpaceBetween mm</td>
        </tr>
    </table>
</div>